### ISSUE TITLE
Support for color types

### ISSUE THREAD

**Issue by kevgeo** [JuliaImages/ImageInpainting.jl#1]
I had read your message on [gitter](https://gitter.im/JuliaImages/Images.jl) about adding support for image types and would like to contribute. But I didn't understand what you meant by image types?  Doesn't the load function take care to convert any image format to a Julia array?

**Comment by juliohm** [comment]
Hi Kevin,

Thanks for your interest in contributing. I think the code won't work
directly with color types. I am not sure though. I highly appreciate a pull
request with possible fixes :)

I'm on vacation this week, but will look at the PR when I'm back.

Thanks again,

**Comment by kevgeo** [comment]
Oh okay, understood. I shall check it out.  :+1:

**Comment by juliohm** [comment]
Dup of #13
