### ISSUE TITLE
Un-pad result on return

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/ImageInpainting.jl#10]
I've finished updating the implementation to use the latest versions of the dependencies. I've also updated the implementation to make better use of OffsetArrays.jl. There is still one missing issue before we can update the test suite and submit a new release. What is the current idiomatic way of un-padding an image that was padded with `padarray`?

```julia
img = zeros(10,10)
pad = padarray(img, Pad(:symmetric, (3,3), (3,3)))

# works but is not officially supported?
padarray(pad, Pad(:symmetric, (-3,-3), (-3,-3)))
```

cc: @johnnychen94 @timholy

**Comment by johnnychen94** [comment]
If `padarray` returns a lazy-evaluated `PaddedArray`(not existed), then using `parent` would be more efficient and applicable.

Since it now returns an `OffsetArray`; I would use `pad[1:end-3, 1:end-3]` or `@view pad[1:end-3, 1:end-3]`.

**Comment by juliohm** [comment]
Thank you @johnnychen94 , I did `pad[1:10,1:10]` to return the original image. More generally in N dimensions:

```julia
start  = CartesianIndex(ntuple(i->1, ndims(img)))
finish = CartesianIndex(size(img))
pad[start:finish]
```
