### ISSUE TITLE
[Question] Is it possible to port this to iOS?

### ISSUE THREAD

**Issue by SocialKitLtd** [JuliaImages/ImageInpainting.jl#12]
Is it possible to port this to iOS?

**Comment by juliohm** [comment]
What do you mean? The code is not working? Is iOS supported by Julia?

**Comment by juliohm** [comment]
I am closing this issue for now, because it looks like you are asking if we can port a whole project to another language.

**Comment by SocialKitLtd** [comment]
Hey buddy, how're things going?
Thanks for the response!

I haven't tested the code, but I was just wondering out loud (maybe you had past experience, etc'). I'm an iOS developer but It's way out of my field. It could be fun to try to run these scripts in iOS tho. 
Are you available for freelance work?

**Comment by juliohm** [comment]
I am not interested, and the issue tracker of our project is not supposed to contain this kind of conversation. Please stop with the spam.
